version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: nrt_minio
    ports:
      - "9000:9000"    
      - "9001:9001"    
    environment:
      MINIO_ROOT_USER: ${minio_user:-default-user}
      MINIO_ROOT_PASSWORD: ${minio_password:-default-password}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Автоматическое создание бакета при старте
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${minio_user:-default-user} ${minio_password:-default-password};
      /usr/bin/mc mb myminio/warehouse;
      exit 0;
      "

  spark-app:
      build: . 
      container_name: my-spark-app
      depends_on:
        - minio
        - createbuckets
      environment:
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=${minio_user:-default-user}
        - MINIO_SECRET_KEY=${minio_password:-default-password}

volumes:
  minio_data: